### ISSUE TITLE
guideline for distributed training

### ISSUE THREAD

**Issue by merlinarer** [OpenMOSS/Language-Model-SAEs#57] opened 2024-11-01 06:38 UTC
Hello, is there a guideline for distributed training ?
I use tp_size=2 and ddp_size=4 with following command:
```
torchrun --nproc_per_node gpu --master_port=10110 examples/programmatic/train.py 
```
error occurs below:
```
[rank5]: Traceback (most recent call last):
[rank5]:   File "Language-Model-SAEs-main/examples/programmatic/train.py", line 101, in <module>
[rank5]:     sparse_autoencoder = language_model_sae_runner(cfg)
[rank5]:   File "Language-Model-SAEs-main/src/lm_saes/runner.py", line 74, in language_model_sae_runner
[rank5]:     sae = SparseAutoEncoder.from_initialization_searching(
[rank5]:   File "/usr/local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[rank5]:     return func(*args, **kwargs)
[rank5]:   File "Language-Model-SAEs-main/src/lm_saes/sae.py", line 646, in from_initialization_searching
[rank5]:     best_norm_coarse = grid_search_best_init_norm(torch.linspace(0.1, 1, 10).numpy().tolist())
[rank5]:   File "Language-Model-SAEs-main/src/lm_saes/sae.py", line 634, in grid_search_best_init_norm
[rank5]:     sae.compute_loss(
[rank5]:   File "Language-Model-SAEs-main/src/lm_saes/sae.py", line 349, in compute_loss
[rank5]:     feature_acts, hidden_pre = self.encode(x, return_hidden_pre=True)
[rank5]:   File "Language-Model-SAEs-main/src/lm_saes/sae.py", line 228, in encode
[rank5]:     x - self.decoder.bias.to_local()  # type: ignore
[rank5]: AttributeError: 'Parameter' object has no attribute 'to_local'
```

**Comment by Hzfinfdu** [comment] 2024-11-01 06:59
Hi, there. We will launch a test soon. Might have introduced some bug here. btw it is recommended not to set ddp_size (default = 1). We will remove this in future versions.

**Comment by merlinarer** [comment] 2024-11-01 07:29
I tried with llama 8b + bs 4096 on a 8*A80G with following setting:
```
torchrun --nproc_per_node 1 + tp-1 ddp-1 run normally on a single gpu but CUDA OOM
torchrun --nproc_per_node 8 + tp-2 ddp-4 'Parameter' object has no attribute 'to_local'
torchrun --nproc_per_node 8 + tp-8 ddp-1 'Parameter' object has no attribute 'to_local'
torchrun --nproc_per_node 8 + tp-1 ddp-1 run normally on all gpus but also CUDA OOM
```
Training a 8b sae should not be a resource-comsuming task, do you have any advice?

**Comment by Hzfinfdu** [comment] 2024-11-01 07:31
Try tp=8 & ddp = 1. We are running tests with tensor parallel

**Comment by Hzfinfdu** [comment] 2024-11-01 07:32
The ideal GPU structure should follow Appendix A in [Llama Scope](https://arxiv.org/pdf/2410.20526). Btw what is your expansion factor (num features)?

**Comment by merlinarer** [comment] 2024-11-01 07:41
> The ideal GPU structure should follow Appendix A in [Llama Scope](https://arxiv.org/pdf/2410.20526). Btw what is your expansion factor (num features)?

expansion factor is 128 default as training example, tp=8 woud lead to error: 'Parameter' object has no attribute 'to_local'

**Comment by merlinarer** [comment] 2024-11-01 07:46
trainging goes well when expansion factor = 16, tp = ddp = 1, but will take 10h for 0.1B token，is this a nomal case ?

**Comment by Hzfinfdu** [comment] 2024-11-01 07:49
Yes. Training an SAE is relatively resource-consuming. This looks reasonable for A80 GPUs. FYI, following Llama Scope's setting, its advised to train 16x SAEs for about 0.6B tokens.

**Comment by Hzfinfdu** [comment] 2024-11-01 08:08
I see it. It seems the issue is you launched training with the original train.py file, which did not initialize nccl backend properly. It should be fine with train_llama_scope.py.

**Comment by merlinarer** [comment] 2024-11-01 09:16
> I see it. It seems the issue is you launched training with the original train.py file, which did not initialize nccl backend properly. It should be fine with train_llama_scope.py.

Acutually I adapt the initial code into tran.py:
```
os.environ["TOKENIZERS_PARALLELISM"] = "false"
dist.init_process_group("nccl")
```
The code would not be started without this.

BTW, I found activation_store iter with transformerlens (as well as in saelens) in [Line](https://github.com/OpenMOSS/Language-Model-SAEs/blob/a05e45a949fa30a3edd1f311bbccd4ebff2fb373/src/lm_saes/sae_training.py#L92)  is really time consuming. Why not to extract acts using pure trasnformers backend like [sae](https://github.com/EleutherAI/sae)? which is about 5x fast.

**Comment by merlinarer** [comment] 2024-11-01 09:24
I guss some oparation in model.run_with_cache_until cost time

**Comment by Hzfinfdu** [comment] 2024-11-01 11:49
Closed as the problem seems to be solved

**Closed by Hzfinfdu** 2024-11-01 11:49 UTC
